### ISSUE TITLE
Use objects instead of arrays in day-names and month-names 

### ISSUE THREAD

**Issue by superbiche** [ZestfulNation/vue-hotel-datepicker#236]
I'm using [Vue-i18n](https://kazupon.github.io/vue-i18n/) and [Weblate](https://weblate.org/fr/) for our translation workflow.  

Unfortunately, Weblate, but many other tools like [dot-object](https://www.npmjs.com/package/dot-object) or even [deepmerge](https://www.npmjs.com/package/deepmerge) can have a hard time handling arrays.  

We can get to the following common sense:  
* `day-names` can be an object like `{ 0: 'Domingo', 1: 'Lunes' }` **or** `{ sunday: 'Domingo', monday: 'Lunes' }`
* `month-names` can be an object like `{ 0: 'January', 1: 'February }` **or** `{ january: 'Enero', february: 'Febrero'}`

I honestly don't know which is best. I find the string-based one easier to read right now, but I'm pretty sure that once we change the code accordingly, integers will be much easier to work with, and allow easier props customization.

**Comment by superbiche** [comment]
I've added this to v4 but maybe v5 huh, this may be too much work and delay v4 without a good enough reason

**Comment by matiasperrone** [comment]
@superbiche What about this?

**Comment by matiasperrone** [comment]
So you may use Object.values or Object.entries javascript functions
