### ISSUE TITLE
New feature: Check disabled dates on the range

### ISSUE THREAD

**Issue by cosmicstays** [ZestfulNation/vue-hotel-datepicker#268]
**Describe the bug**
I have passed certain values to datepicker as disabled dates and it is showing the same as blocked dates. I Have set min nights to 5. When I click on a date just before the blocked date, and select the range the datepicker is still allowing to select a range with the blocked dates.

**To Reproduce**
1. Add blocked dates [2021-03-02, 2021-03-03]
2. Set min nights to 5
3. Select date 2021-03-01 and select 5 nights.
4. The datepicker lets user choose the blocked dates as well

**Expected behavior**
If minimum nights required not available in a row, then disable all future dates
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Browser [chrome, safari] 
<img width="814" alt="Screenshot 2021-02-24 at 8 23 48 PM" src="https://user-images.githubusercontent.com/72752651/109018694-57a23e80-76de-11eb-94c5-a36f5764006f.png">

**Comment by matiasperrone** [comment]
This is not a bug exactly, is a control of the blocked days, blocked days can be a number of uses, for instance when you don't want that anyone book on those days, for instance not checkins or checkouts on certain days, but they could be part of a booking.

Probably you should use bookings instead.

**Comment by cosmicstays** [comment]
I tried using it with bookings prop but it still behaves the same way. Ideally when selecting checkin date the datepicker should disable all the dates that are not possible to be considered checkout date based on restrictions like min nights and available dates.

**Comment by LucaGiardi20** [comment]
Hi @matiasperrone , i also need the same behaviour described by @cosmicstays, there's a way to implement it through props or with some javascript? 

I've tried with blockedDays and bookings but it still behaves the same way.

Thanks

**Comment by matiasperrone** [comment]
> 

hi

**Comment by matiasperrone** [comment]
Close for lack of response
