### ISSUE TITLE
'booking-clicked' event not fired if booking duration is one night

### ISSUE THREAD

**Issue by Merton** [ZestfulNation/vue-hotel-datepicker#276]
**Describe the bug**
If you have a booking which lasts over 2 days, and 1 night. Ie, start date:  `2021-04-15` and end date `2021-04-16`, the booking-clicked event is not fired.

**To Reproduce**
1. Create bookings consisting of at least 1 booking which lasts 1 night: ` [{ checkInDate: '2021-04-15', checkOutDate: '2021-04-16', style: xxx}]`
2. Try to click either the 15th, or the 16th. Clicking the 15th does not trigger any event, and clicking the 16th triggers a new check in selection

**Expected behavior**
At least, clicking the check in date (15th) to trigger booking clicked event. Ideally if 16th is clicked, both events (check in changed and booking clicked) are triggered

**Screenshots**
![image](https://user-images.githubusercontent.com/25505506/112847524-10bdb500-909f-11eb-958d-a84ccffa537c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox / Chrome
 - Version FF 87 / Chrome 89.0.4389.90

**Comment by matiasperrone** [comment]
Did you checked on the last version?

**Comment by matiasperrone** [comment]
Hi @Merton!! long time...

Sorry for the late response.
The "booking-clicked" event, only works with bookings, if the bookings prop was provided, then it shows those dates differently, and if the user click on one of those the event fires.

Best!
