### ISSUE TITLE
Half day documentation

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [ZestfulNation/vue-hotel-datepicker#301]
Hello,
Could you please put out some documentaion on the half day use?
I can read : "Allows to have half a day, if you have check in at noon and checkout before noon" but I can't see how to implement this.

I'm having some issues with disabled dates.

EXAMPLE:
I have bookings: 
**from the 15th to the 16th of the month
from the 17th to the 21st of the month
from the 23rd to the 24th of the month
from the 25th to the 26th of the month**

So the user should be able to book:
**from the 16th to the 17th of the month
from the 21st to the 23rd of the month
from the 24th to the 25th of the month**

My disabled dates calculation goes like:
`$period = CarbonPeriod::create($booking->starts_at, $booking->ends_at);`
which disables too many dates

If I try something like:
`$period = CarbonPeriod::create(Carbon::parse($booking->starts_at)->addDay(), Carbon::parse($booking->ends_at)->subDay());`
It re-enables all the dates I need but the ranges I can select are too wide, now I can book **from the 21st to the 25th**.

Given the upper example I shouldn't be able to book: 
**from the 21st to the 25th**
but only:
**from the 21st to the 23rd**
and
**from the 24th to the 25th**

So the only way to solve this should be Half days.
Could you document on how to get this done please?

**Comment by matiasperrone** [comment]
Hi @ShapesGraphicStudio did you fixed your issue some how?
Do you want to share?

**Comment by ShapesGraphicStudio** [comment]
Hello,
Still not fixed unfortunately.
I think I might have to look for another component as we are missing bookings.

**Comment by matiasperrone** [comment]
Nice catch.

**Comment by matiasperrone** [comment]
What version are (or were) you using?
