### ISSUE TITLE
Scroll gesture shifts months

### ISSUE THREAD

**Issue by shinesoftware** [ZestfulNation/vue-hotel-datepicker#307]
Hello, first of all thanks for your vue component. 
When I try to scroll down the page in my mobile I can see the months changes. Why this happens? How to disable this feature?

![Peek 15-03-2022 18-53](https://user-images.githubusercontent.com/1553035/158441149-faa43ee3-d0bb-4a84-b898-ec45048a38c1.gif)

**Comment by matiasperrone** [comment]
I am not sure, since I was not the one developing this "feature" (or is it a bug?)
Is it possible that you may change horizontally unintentionally?...

Can you search the code responsible for this behavior?

**Comment by matiasperrone** [comment]
@shinesoftware hello... coming back from ReactJS (My day work is on that technology now)

I'll try to fix it.
