### ISSUE TITLE
Suggestion: Show week names on mobile/tablet

### ISSUE THREAD

**Issue by cocomode18** [ZestfulNation/vue-hotel-datepicker#308]
The week names for mobile/tablet devices are hidden by css class `vhd__hide-up-to-tablet`.  
https://github.com/ZestfulNation/vue-hotel-datepicker/blob/main/src/DatePicker/components/WeekRow.vue#L2

Is there a reason to hide them?  
I'd prefer them to be visible on both pc and mobile/tablet devices, or at least make them selectable by props.

**Comment by softopia-tech** [comment]
I have the same question, also when we select first date in mobile it's not getting highlighted

**Comment by matiasperrone** [comment]
Hi... sorry... I didn't have the time to dedicate to the project.
Is this more like a enhancement, right?

**Comment by softopia-tech** [comment]
> Hi... sorry... I didn't have the time to dedicate to the project. Is this more like a enhancement, right?

Yes, we can count it in enhancement, but the highlight first date on select in mobile is working fine on demo page but not working with the latest release of the package.

**Comment by matiasperrone** [comment]
This feature will be available in the next version v4.6

**Comment by matiasperrone** [comment]
Done
