### ISSUE TITLE
Issue when closing calendar on mobile (v3.0.10)

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [ZestfulNation/vue-hotel-datepicker#321]
Hello, 

I'm still on 3.0.10 version here.

Using Desktop, it's OK, when I select arrival date, and close the calendar to reopen it nothing changes.

But using mobile, when I close calendar, the dates somehow resets and I can select dates that I should not be able to select.

To illustrate this:

First calendar opening is OK

<img width="447" alt="Capture d’écran 2023-03-16 à 12 36 42" src="https://user-images.githubusercontent.com/4211076/225605956-03069e81-1b35-4aeb-a227-812f9c726f66.png">

If I select March 26th I can't select departure as 26th can't be an arrival day (by the way, half days do not have specific css class to show if it's just an arrival open date or departure open date).

<img width="446" alt="Capture d’écran 2023-03-16 à 12 37 14" src="https://user-images.githubusercontent.com/4211076/225606377-403f6de4-c994-4988-acd0-784c77ecbde7.png">

If I close the calendar to reopen it arrival date is still selected but all other dates reappear which allows the user tu select March 28th for departure which leads to double / overlapping bookings.

<img width="444" alt="Capture d’écran 2023-03-16 à 12 37 54" src="https://user-images.githubusercontent.com/4211076/225606724-692d07b8-745c-4235-add3-5904ee016c4d.png">

<img width="446" alt="Capture d’écran 2023-03-16 à 12 45 02" src="https://user-images.githubusercontent.com/4211076/225607102-b8178482-8d1e-4632-82c2-3d177963681b.png">

This is only happening on mobile layout.
Any idea on how to solve this?
Is an event triggered on close only on mobile?

**Comment by matiasperrone** [comment]
Sorry again @ShapesGraphicStudio... 

I have not idea without checking that out myself.
I am not going to fix any of the old versions anyway, you're welcome to provide a PR, I will merge ASAP.
I'll provide new patches for the last v4 version and if I have the time I will work in the Vue 3 version.
Anyway, you can contact me here:

- https://calendly.com/matias-perrone.
- Private Message using X [@matup](https://x.com/matup)
- Go to https://www.globalinnovation.com.ar/ and check at the footer, you will see an email and a phone number.
