### ISSUE TITLE
Disabled dates issue when using halfDay after upddate

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [ZestfulNation/vue-hotel-datepicker#323]
Hello,
I just updated to latest version.
I'm facing an issue as I'm able to select a range with disabled dates in it when HalfDay is set to true.

On first opening, calendar shows nicely with disabled dates and half days:

<img width="727" alt="Capture d’écran 2023-03-16 à 18 04 28" src="https://user-images.githubusercontent.com/4211076/225697439-68008395-8e47-40cb-948c-766dc508dd0c.png">

I can see that if I select March 24th, the max end date of my range should be March 27.
But wwhen selecting March 24th, the max date is set to April 8th wich is the day before a full disabled date.
Seems like it does not recognize half days here.

<img width="725" alt="Capture d’écran 2023-03-16 à 18 04 44" src="https://user-images.githubusercontent.com/4211076/225697989-7536c6ae-9723-409e-b531-129c5bfd447a.png">

And as we cans see in last screenshot, I'm able to select a booking from March 24th to APril 8th which can lead to double / overlapping bookings.

<img width="729" alt="Capture d’écran 2023-03-16 à 18 04 58" src="https://user-images.githubusercontent.com/4211076/225698197-08244c4a-4148-400e-8f12-3639ced66326.png">

Any idea on how to solve this please?

BTW, I'm missing the icons here, maybe because it's my local config?

**Comment by matiasperrone** [comment]
Hello @ShapesGraphicStudio,

Sorry for the SUUUUUPER late response. Last year was really bad for me, and there are no other devs maintaining this component. 
Yeah, this is a known issue... fixing it is more complex than what it seems from my side.

The current code is complex, should be simple but is not.
Remember you can always push a PR for this.

So in the end what did you do with this?

**Comment by matiasperrone** [comment]
I remembered! Set the timezone so it can work accordingly.
