### ISSUE TITLE
When Bookings are present disabled Dates are not there or partially there. 

### ISSUE THREAD

**Issue by goors** [ZestfulNation/vue-hotel-datepicker#324]
**Describe the bug**
When bookings is present with disabledDates, disabled dates are not visible.

**To Reproduce**
1. Set booked dates to any range
2. Set disabledDates to any range

**Expected behavior**
I should be able to see disabled dates and not be able to click on them.

**Screenshots**
Disabled dates
[<img src="https://i.ibb.co/Jd8kDx6/Screenshot-2023-05-04-at-22-47-01.png">](https://ibb.co/9vBYQwK/)

Bookings

[<img src="https://i.ibb.co/YbVj2Mg/Screenshot-2023-05-04-at-22-47-21.png">](https://ibb.co/9vBYQwK/)

As you can see, when Bookings are present you see some disabled dates.

**Comment by goors** [comment]
Also, halfDay if true, you can go on and select from 6th to any day in the future. But 8th is kind of skipped, and it is disabled date.

**Comment by goors** [comment]
As far as i can tell you can not have both, disabled days and bookings. This function is preventing that:

```
`if (this.sortBookings.length === 0) {///} `will never fire since you got bookings. That is part of that method `createHalfDayDates(_baseHalfDayDates)`

**Comment by goors** [comment]
I have check it again:

1. set disabled dates
2. setTimeout to 5 seconds and then add bookings 

Result is disabled dates are gone beccause of that condition.

Only solution is to remove that and let that for loop fire always.

**Comment by matiasperrone** [comment]
Hi @goors,

I didn't have time to expend on this project yet, or read y
Do you were able to check what's wrong? do you have code to fix this that may respect back compatibility?

**Comment by matiasperrone** [comment]
Hi @goors so can you give me some update on this?

**Comment by matiasperrone** [comment]
Check my answer here https://github.com/ZestfulNation/vue-hotel-datepicker/issues/268
