### ISSUE TITLE
Suggestion: Show week number

### ISSUE THREAD

**Issue by webartistse** [ZestfulNation/vue-hotel-datepicker#81]
Would like option to show the number of the week to the left in the calendar. Very common that you relate to the week number in parts of Europe.

**Comment by amulchinock** [comment]
@webartistse Could you elaborate?

Do you mean that the datepicker should show the current week in the year, when selecting dates?
(i.e https://www.epochconverter.com/weeks/2018)

**Comment by webartistse** [comment]
@amulchinock Sure! Many apps or components solves this by adding some label or similar on the current row. I attached an example here how Calendar in MacOS shows this. The reason many users needs this is that its common to say/know that you have vacation week 28-31 but you dont know exact dates. At least this is common in Scandinavia and some parts of europe.

![macos calendar](https://user-images.githubusercontent.com/3966652/46700214-7a6e4e00-cc1c-11e8-8d49-72b11f16899b.png)

**Comment by amulchinock** [comment]
@webartistse Ahh - I think I understand.
So, if I said that I was going on holiday from the 9th to the 16th of October 2018 - I could also be more vague and say that I was going from the 41st - 42nd week?

**Comment by amulchinock** [comment]
@webartistse Interesting! In British English (I'm from England), we'd say something along the lines of "I'm going on holiday around the 25th of October, for two weeks".

In your opinion, what would be the best way of handling this? We could create a property for the datepicker for showing week numbers (something like `:showWeekNumbers="someVariable_or_String"`
Would that work for you?

I'd be interested to hear @krystalcampioni view on this :)

**Comment by krystalcampioni** [comment]
Interesting! I've been to Stockholm recently and a friend was also talking about how week numbers are used there, even for parking signs. I think a boolean prop `showWeekNumbers` would make sense for this 👍

**Comment by webartistse** [comment]
@amulchinock @krystalcampioni That would be awesome!

**Comment by matiasperrone** [comment]
Hi guys! seems that this feature went 🧊.

I am working on v3. I think it should be easier to add it if you provide me with a PR... still interested?

**Comment by matiasperrone** [comment]
Hi! this I think more for v4.1 (v4.0 is right around the corner).
v4 will have a complete rewrite in html and many bugfixes. I am waiting a PR anytime...

**Comment by matiasperrone** [comment]
Also I didn't have the time.

**Comment by mariusa** [comment]
> In British English (I'm from England), we'd say something along the lines of "I'm going on holiday around the 25th of October, for two weeks".

Same here in Romania. I never heard people saying "going on week 37" -- huh?

**Comment by matiasperrone** [comment]
Same here in Argentina, but there are a number of countries.

**Comment by matiasperrone** [comment]
I am sorry but I am going to remove this feature from the v4 in order to be able to finish the final release

**Comment by kasperlegarth** [comment]
@matiasperrone I have taken the liberty to take this task on me. As I could see it was hard (understandable) for you to find the time for this task.
I hope my code is clear and obvious, or let me know so I can make the needed adjustments.

For any fellow Scandinavians, it is us that need this functionality the most, the implementation of the week numbers is pretty well tested. I first implemented this a few years ago on the ["sol og strand" website](https://www.sologstrand.dk/) In the booking bar on the front page. There have been no bugs to my knowledge with the week numbers in the two years' time.

**Comment by matiasperrone** [comment]
I am cheking out PR #317 to solve this enhancement.

**Comment by matiasperrone** [comment]
Done in v4.6

**Comment by matiasperrone** [comment]
working on the build please wait

**Comment by matiasperrone** [comment]
@webartistse @mariusa @krystalcampioni @amulchinock I hope this bring joy!
Happy new year!
